#服务端口号
server:
  port: 15015
  servlet:
    context-path: /
    session:
      timeout: 7200s
  tomcat:
    max-threads: 1000

#注册
spring:
  application:
    name: demo-application
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: cxp-dev
#        file-extension: yaml
#        group: DEFAULT_GROUP
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: cxp-dev

  #mysql
  #  datasource:
  #    url: jdbc:mysql://10.254.1.11:3306/uat_ylst?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
  #    username: uat_ylst
  #    password: Rce6fDeRsQBG6Hzu
  #    driver-class-name: com.mysql.cj.jdbc.Driver
  #mysql
#  datasource:
#    url: jdbc:mysql://10.254.1.11:3306/uat-yls-survey?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowPublicKeyRetrieval=true&useSSL=false
#    username: uat_yls
#    password: eOftMvcz!VEGU5%7
#    driver-class-name: com.mysql.cj.jdbc.Driver


#  redis:
#    database: 0
#    host: 8.142.178.241
#    password: muma2020
#    port: 6379

  session:
    redis:
      namespace: planetg
    store-type: redis


  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  #es配置
#  elasticsearch:
#    uris: http://localhost:9200
#    password: 123456
#    username: elastic
#    connection-timeout: 10s
#    socketTimeout:10000
#    address:http://localhost:9200

#log4j
logging:
  config: classpath:log4j.xml
  level:
    com.ssi.collection: trace
    tracer: trace
easy-es:
  host:127.0.0.1
  port:9200
  enable: true #默认为true,若为false则认为不启用本框架
  address : 127.0.0.1:9200 # es的连接地址,必须含端口 若为集群,则可以用逗号隔开 例如:127.0.0.1:9200,127.0.0.2:9200
#  username: elastic #若无 则可省略此行配置
#  password: WG7WVmuNMtM4GwNYkyWH #若无 则可省略此行配置
  socketTimeout: 5000 # 请求通信超时时间 单位:ms 在平滑模式下,由于要迁移数据,用户可根据数据量大小调整此参数值大小,否则请求容易超时导致索引托管失败,建议您尽量给大不给小,跟那玩意一样,大点没事,太小你懂的!
    global-config:
      process_index_mode: manual #smoothly:平滑模式, not_smoothly:非平滑模式, manual:手动模式
      async-process-index-blocking: true # 异步处理索引是否阻塞主线程 默认阻塞
      distributed: false # 项目是否分布式环境部署,默认为true, 如果是单机运行可填false,将不加分布式锁,效率更高.

#mybatis-plus:
#  configuration:
#    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  global-config:
#    db-config:
#      id-type: auto
#      logic-delete-value: now()
#      logic-not-delete-value: 'null'
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.planetg.survey.restructure.model.entity
#

#
resttemplate:
  connection:
    timeout: 150000
  read:
    timeout: 150000


